[config]
[templates.waybar]
input_path = "~/.config/waybar/template.css"
output_path = "~/.config/waybar/colours.css"
[templates.vicinae]
input_path = './templates/vicinae.toml'
output_path = '~/.local/share/vicinae/themes/matugen.toml'
post_hook = 'vicinae theme set matugen'
