[config]
[templates.waybar]
input_path = "~/.config/waybar/template.css"
output_path = "~/.config/waybar/colours.css"
post_hook = 'killall -SIGUSR2 waybar'

[templates.hyprland]
input_path = './templates/hyprcolour.conf'
output_path = '~/.config/hypr/modules/colour.conf'
post_hook = 'hyprctl reload'

[templates.wlogout]
input_path = './templates/wlogout.css'
output_path = '~/.config/wlogout/colours.css'

[templates.swaync]
input_path = "./templates/colours.css"
output_path = "~/.config/swaync/colours.css"
post_hook = "swaync-client -rs"

[templates.hyprwave]
input_path = "~/.config/waybar/template.css"
output_path = "~/.local/share/hyprwave/colours.css"
post_hook = 'killall -SIGUSR2 hyprwave'

[templates.rofi]
input_path = "~/.config/matugen/templates/matugen.rasi"
output_path = "~/.config/rofi/matugen.rasi"
