[config]
[templates.waybar]
input_path = "~/.config/waybar/template.css"
output_path = "~/.config/waybar/colours.css"
post_hook = 'killall -SIGUSR2 waybar'

[templates.vicinae]
input_path = './templates/vicinae.toml'
output_path = '~/.local/share/vicinae/themes/matugen.toml'
post_hook = 'vicinae theme set matugen'

[templates.hyprland]
input_path = './templates/hyprcolour.conf'
output_path = '~/.config/hypr/modules/colour.conf'
post_hook = 'hyprctl reload'

[templates.wlogout]
input_path = './templates/wlogout.css'
output_path = '~/.config/wlogout/colours.css'

[templates.hyprlock]
input_path = './templates/hyprlock.conf'
output_path = '~/.config/hypr/hyprlock.conf'

[templates.swaync]
input_path = "./templates/colours.css"
output_path = "~/.config/swaync/colours.css"
post_hook = "swaync-client -rs"

[templates.fastfetch]
input_path = "./templates/config.jsonc"
output_path = "~/.config/fastfetch/config.jsonc"

[templates.hyprwave]
input_path = "~/.config/waybar/template.css"
output_path = "~/.local/share/hyprwave/colours.css"
post_hook = 'killall -SIGUSR2 hyprwave'


